### ISSUE TITLE
element.pivotUI() is not a function?

### ISSUE THREAD

**Issue by mbattistello** [ErickRuano/angular-pivot#3]
Im getting this error when I try to integration this with my app. I think I might have an issue with the order I am loading the various dependencies? 

Here are my imports in my index.html file. Any idea what might be issue?

<link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="app.css">
    <link rel="stylesheet" href="dashboard.css">
    
    
    <link rel="stylesheet" href="bower_components/jquery-ui/themes/smoothness/jquery-ui.min.css">
    
    <script src="bower_components/angular/angular.min.js"></script>
    
    <script src="bower_components/jquery/dist/jquery.min.js"></script>
    <script src="bower_components/jquery-ui/jquery-ui.min.js"></script>
    <script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="bower_components/angular-resource/angular-resource.min.js"></script>
    <script src="bower_components/angular-route/angular-route.min.js"></script>
    <script src="bower_components/angular-bootstrap/ui-bootstrap.min.js"></script>
    <script src="bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js"></script>
    
    
    
    <link href="bower_components/pivottable/dist/pivot.css" rel="stylesheet" type="text/css" />
    <script src="bower_components/pivottable/dist/pivot.js"></script>
    <script src="bower_components/angular-pivottable/dist/angular-pivot.js"></script>
    
    <script src="core/core.module.js"></script>
    
    <script src="core/authenticator/authenticator.module.js"></script>
    <script src="core/authenticator/authenticator.service.js"></script>
    
    <script src="core/database/database.module.js"></script>
    <script src="core/database/database.service.js"></script>
    
    <script src="core/transaction/transaction.module.js"></script>
    <script src="core/transaction/transaction.service.js"></script>
    
    <script src="login/login.module.js"></script>
    <script src="login/login.component.js"></script>
    
    <script src="dashboard/dashboard.module.js"></script>
    <script src="dashboard/dashboard.component.js"></script>
    
    <script src="database/database.module.js"></script>
    <script src="database/database.component.js"></script>
    
    <script src="app.module.js"></script>
    <script src="app.config.js"></script>
    <script src="app.run.js"></script>

**Comment by ErickRuano** [comment]
Hi @mbattistello,

Sorry for late response.  Have you gotten around this yet? Your dependency load order seems fine, though I usually load jQuery before angular, that shouldn't be affecting the library.

I'll take a look later today but in the meantime, try using loading jQuery v2.1.4 and jQuery-UI v1.11.4 which are the versions I'm currently running in production along with angular-pivot?.

**Comment by Chanrith** [comment]
Hello @mbattistello, @ErickRuano 

I ran into this exact issue and it turns out loading the jQuery dependencies before loading angular fixed the problem for me.  Just thought I'd share for anyone else that may be facing the same problem.

**Comment by ErickRuano** [comment]
Since my recommendation was tested by @Chanrith and actually fixed the bug I'll close the issue with this solution.

> I usually load jQuery before angular
> loading the jQuery dependencies before loading angular fixed the problem

**Comment by ErickRuano** [comment]
Since my recommendation was tested by @Chanrith and actually fixed the bug I'll close the issue with this solution.

> I usually load jQuery before angular

> loading the jQuery dependencies before loading angular fixed the problem
